trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPush
  displayName: 'Build and push Docker image'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker'   
      repository: 'testccc24/testccc24:latest' 
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'

- job: DeployToAzure
  displayName: 'Deploy to Azure Web App'
  dependsOn: BuildAndPush
  steps:
  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'servtest'  
      appName: 'mypythonapp24' 
      containers: 'docker.pkg.github.com/testccc24/testccc24/my-python-app'

