trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'docker'   
    repository: 'Testccc24/my-python-app' 
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '82040efc-3d5a-40bc-98e0-1e6f791d7f34'  
    appName: 'mypythonapp24' 
    containers: 'docker.pkg.github.com/testccc24/testccc24/my-python-app'   
