trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'docker'   
    repository: 'testccc24/testccc24' 
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '67494e9f-ee8c-4893-930c-6ceed3627e14'  
    appName: 'mypythonapp24' 
    containers: 'docker.pkg.github.com/testccc24/testccc24/my-python-app'   
